w = dw.wrangle()

/* Split data repeatedly on newline  into  rows */
w.add(dw.split().column(["data"])
	.table(0)
	.status("active")
	.drop(true)
	.result("row")
	.update(false)
	.insert_position("right")
	.row(undefined)
	.on("\n")
	.before(undefined)
	.after(undefined)
	.ignore_between(undefined)
	.which(1)
	.max(0)
	.positions(undefined)
	.quote_character(undefined)
)

/* Split data repeatedly on 'tab' */
w.add(dw.split().column(["data"])
	.table(0)
	.status("active")
	.drop(true)
	.result("column")
	.update(false)
	.insert_position("right")
	.row(undefined)
	.on("\t")
	.before(undefined)
	.after(undefined)
	.ignore_between(undefined)
	.which(1)
	.max(0)
	.positions(undefined)
	.quote_character(undefined)
)

/* Promote row 1  to header */
w.add(dw.set_name().column([])
	.table(0)
	.status("active")
	.drop(true)
	.names([])
	.header_row(0)
)

/* Cut from pos on 'a' */
w.add(dw.cut().column(["pos"])
	.table(0)
	.status("active")
	.drop(false)
	.result("column")
	.update(true)
	.insert_position("right")
	.row(undefined)
	.on("a")
	.before(undefined)
	.after(undefined)
	.ignore_between(undefined)
	.which(1)
	.max(1)
	.positions(undefined)
)

/* Delete  rows where pos is null */
w.add(dw.filter().column([])
	.table(0)
	.status("active")
	.drop(false)
	.row(dw.row().column([])
	.table(0)
	.status("active")
	.drop(false)
	.conditions([dw.is_null().column([])
	.table(0)
	.status("active")
	.drop(false)
	.lcol("pos")
	.value(undefined)
	.op_str("is null")
])
)
)

/* Fill categoria  with values from above */
w.add(dw.fill().column(["categoria"])
	.table(0)
	.status("active")
	.drop(false)
	.direction("down")
	.method("copy")
	.row(undefined)
)

/* Fill n_categoria  with values from above */
w.add(dw.fill().column(["n_categoria"])
	.table(0)
	.status("active")
	.drop(false)
	.direction("down")
	.method("copy")
	.row(undefined)
)

/* apply transforms to data.  data can be a string, datatable or array of datatables */
w.apply(data)
